"use client";
import { useMemo, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { EnglishProduct, ProductCategory } from "@/lib/types";
import { ArrowRightIcon } from "@/components/icons/Icons";
export function EnglishProductCard({ product, priority = false }: { product: EnglishProduct; priority?: boolean }) {
  return <article className="group flex flex-col overflow-hidden rounded-xl border border-[#D9D5CD] bg-[#F8F6F2] text-[#191D20]"><Link href={`/en/products/${product.slug}`} aria-label={`Explore ${product.name}`} className="relative block aspect-[4/3] bg-[#EAE7E1]">{product.image ? <Image src={product.image} alt={product.name} fill priority={priority} sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-contain p-8 mix-blend-multiply transition-transform duration-500 group-hover:scale-[1.04]" /> : <span className="absolute inset-0 flex items-center justify-center text-sm">Product image unavailable</span>}</Link><div className="flex flex-1 flex-col p-6"><p className="mb-4 text-xs text-[#62635F]">{product.standards.slice(0,2).join(" / ")}</p><h3 className="text-xl font-medium leading-snug tracking-tight"><Link href={`/en/products/${product.slug}`} className="hover:text-[#96350B]">{product.name}</Link></h3><p className="mb-6 mt-3 text-sm leading-relaxed text-[#62635F]">{product.shortDescription}</p><Link href={`/en/products/${product.slug}`} className="mt-auto flex items-center justify-between gap-4 border-t border-[#191D20]/15 pt-5 text-sm font-medium hover:text-[#96350B]">Explore product <ArrowRightIcon className="h-4 w-4" /></Link></div></article>;
}
export function EnglishProductGrid({ products, categories, initialCategory, initialQuery = "" }: { products: EnglishProduct[]; categories: ProductCategory[]; initialCategory?: string; initialQuery?: string }) {
  const [category, setCategory] = useState(categories.some(item => item.id === initialCategory) ? initialCategory! : "all");
  const [query, setQuery] = useState(initialQuery);
  const filtered = useMemo(() => products.filter(product => (category === "all" || category === product.categorySlug || categories.find(item => item.id === category)?.name === product.category) && [product.name, product.shortDescription, ...product.materials, ...product.standards].some(value => value.toLowerCase().includes(query.trim().toLowerCase()))), [products, categories, category, query]);
  return <div><div className="mb-8 space-y-6 border-y border-[#191D20]/15 py-7"><label className="block max-w-xl"><span className="sr-only">Search products, materials or standards</span><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search products, materials or standards" className="w-full rounded-lg border border-[#D9D5CD] bg-[#F8F6F2] px-5 py-4 text-sm focus:outline-none focus:ring-2 focus:ring-rust" /></label><div role="group" aria-label="Product categories" className="flex flex-wrap gap-2">{[{id:"all",name:"All products"},...categories].map(item => <button key={item.id} type="button" aria-pressed={category===item.id} onClick={() => setCategory(item.id)} className={`rounded-full border px-4 py-2.5 text-xs font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-rust ${category===item.id ? "border-[#191D20] bg-[#191D20] text-white" : "border-[#CFCBC3] text-[#4D514B] hover:border-[#B7410E]"}`}>{item.name}</button>)}</div></div><div className="mb-8 flex justify-between gap-4 text-xs text-[#62635F]"><p role="status" aria-live="polite">{filtered.length} products</p>{(category!=="all" || query) && <button type="button" onClick={() => {setCategory("all");setQuery("");}} className="text-[#96350B] underline">Clear filters</button>}</div>{filtered.length ? <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map((product,index) => <EnglishProductCard key={product.id} product={product} priority={index<3} />)}</div> : <div className="rounded-xl border border-[#D9D5CD] py-16 text-center"><p className="mb-4">No products match your search.</p><Link href="/en/contact" className="text-[#96350B] underline">Ask about custom manufacturing</Link></div>}</div>;
}
